POST  http://0.0.0.0:8000/signup
Content-Type: application/json

{"username": "qhuy4919-01", "password": "quanghuy4919", "email": "quanghuy4919@gmail.com"}

###

POST http://0.0.0.0:8000/login
Content-Type: application/json

{"username": "qhuy4919-01", "password": "quanghuy4919"}

###
POST http://0.0.0.0:8000/logout
Content-Type: application/json

{"username": "qhuy4919-01", "password": "quanghuy4919"}
